### ISSUE TITLE
The items don't seem to be enabled

### ISSUE THREAD

**Issue by mandaris** [ksalzke/completed-task-report-omnifocus-plugin#1]
<img width="417" alt="image" src="https://user-images.githubusercontent.com/86337/112928970-678db380-90cc-11eb-95f6-0c9dc78a8aa9.png">

I tried both local and OmniFocus in the Cloud.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/86337/112929165-be938880-90cc-11eb-94d6-8ab80d6b57a4.png">

Is there something that I should look into

**Comment by ksalzke** [comment]
Hi @mandaris!

The validation for the plugin is configured such that it shows only when no tasks nor projects are selected. I did it this way so that it didn't clog up the 'share' menu on iOS.

If you would prefer it to show all the time, you can edit the `sendToDayOne.js` and/or `sendToDrafts.js` files and change `return selection.tasks.length == 0 && selection.projects.length == 0` to `return true`.

Let me know if this helps to solve your problem!

**Comment by mandaris** [comment]
Thank you for responding!
