### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by carlisia** [ksalzke/completed-task-report-omnifocus-plugin#5]
Hi @ksalzke, this is such a useful automation, thank you!

I can't get mine to work though. I installed both plugins. The buttons are clickable, I choose a date, but using either copy to clipboard or drafts doesn't work.

Any pointer for how I could troubleshoot this? Thank you!

![2021-06-28 at 8 36 PM](https://user-images.githubusercontent.com/16508/123733573-9abd1b80-d850-11eb-9c73-eecb56025eb9.png)

**Comment by ksalzke** [comment]
Hi @carlisia! It doesn't sound like it's that useful at the moment for you!

It all looks like it's installed correctly. Could you just click on the 'i' icon next to 'Completed Task Report' and check that it's version 2.0.0 you have installed? (Just to make sure we're working with the same version.)

Could you also confirm which OmniFocus version you have?

When you choose 'Copy To Clipboard' do you get a pop-up to indicate that the report has been copied to the clipboard, or just nothing?

What date(s) are you selecting? (Maybe that will help me replicate the issue.)

To be honest I'm not really sure what might be causing the problem (it's working for me!) but I have two thoughts:
1. Maybe there are no tasks for the day you're selecting?
2. The plugin does take some time to build the report (you might get a spinning cursor for a little while before anything happens), so it's possible maybe it needs more time?

**Comment by carlisia** [comment]
Hi! Thank you for you time in getting back. Also: darn it! If you come up with any other thing to check please let me know!

I answered your questions below, it seems that everything checks out. One more data point apropo of nothing: when I type `drafts5://create?text={{LIST}}` on my browser I get a prompt to open Drafts and `{{LIST}}` gets inserted into a note, as expected.

I haven't tried the Day One, that's why I haven't mentioned it.

See the screenshot below. I have completed tasks for "yesterday", selected "yesterday", clicked on 'Continue", then nothing happens from there, no spinning wheel, no indicator, nothing.


Omnifocus version: 3.11.7 (v149.14.0)
Drafts version: 27.0.11

![image](https://user-images.githubusercontent.com/16508/123814791-d684cf00-d8aa-11eb-892d-5c29dbd7f045.png)


![image](https://user-images.githubusercontent.com/16508/123814500-96bde780-d8aa-11eb-8bcc-12c09b8a9ef5.png)

**Comment by ksalzke** [comment]
Hmmm, 'yesterday' is definitely working for me, and those are the same versions as I have.

Some other thoughts to help us troubleshoot:

- Does it work if you select something other than 'Yesterday'? (I'm assuming you've tried this already, but perhaps not.)
- Have you changed the `completedReportConfig` file? I wonder whether there might be an issue with the tags/folders it is looking for, but not finding (because they're not in your database) and matching with something else. If not, try changing both `tagsToExclude` and `projectsToExclude` to `return []` instead of what's there right now.
- You could uninstall and reinstall from https://github.com/ksalzke/completed-task-report-omnifocus-plugin/tree/a5b84771de28f1a6a94ceb4f3157ca6c7e849f54. This is a slightly older version, before some structural changes were made to the plugin. (This doesn't have the ability to copy to the clipboard, but otherwise the actual functionality hasn't changed much.) If you can get that working with Drafts then we'll at least know that I broke something in making those changes!


Otherwise: let me know, and I'll see what else we can do.

Honestly since I first wrote this plugin a fair bit has been added to the Omni Automation API, and I've learned some things, so the code could probably be refactored and streamlined a bit. Maybe if I do that project I will magically fix the bug for you!

**Comment by carlisia** [comment]
Whoa, it was the `projectsToExclude`! I changed it to the code below.

Thank you so much!

```
completedReportConfig.projectsToExclude = () => {
    // Edit the below to configure the projects that should be ignored -
    // tasks from these projects will be excluded from the report
    // THIS SHOULD BE AN ARRAY OF PROJECTS

    return []
  }
```

**Comment by carlisia** [comment]
I also changed the code to create the draft with a tag: `const urlTemplate = 'drafts5://create?text={{LIST}}&tag=status'`.

**Comment by carlisia** [comment]
I forgot to close the issue, closing now. Much appreciate your help!

**Comment by ksalzke** [comment]
No worries, thank you! So glad you got it working!

I'd like to rework those options into a Preferences menu, and hopefully once I do that it should remove this as a potential issue! (I should probably also consider making an empty array the default there.)

**Comment by carlisia** [comment]
That sounds sweet, I'll def would want to upgrade. I marked to watch everything in this repo, hopefully you will do upgrades via a PR so GH notifies ppl who are watching!
